---
# tasks file for user_management
- name: Crear grupos
  group:
    name: "{{ item }}"
    state: present
  loop: "{{ user_accounts | map(attribute='groups') | flatten | unique }}"
  become: true

- name: Crear usuarios
  user:
    name: "{{ item.username }}"
    password: "{{ item.password | password_hash('sha512') }}"
    groups: "{{ item.groups }}"
    state: present
  loop: "{{ user_accounts }}"

# - name: Eliminar usuarios
#   user:
#     name: "{{ item.name }}"
#     state: absent
#   loop: "{{ user_accounts }}"
#   when: item.state == 'absent'
...

